version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test1234

  bank-go:
    image: bank-go
    restart: always
    ports:
      - 8000:8000
    links:
      - db
    environment:
      POSTGRES_HOST: db

